/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package temperatureconverter;

import javax.swing.*;

/**
 *
 * @author OmitNomis
 */
public class ConverterGUI extends javax.swing.JFrame {

    /**
     * Creates new form ConverterGUI
     */
    public ConverterGUI() {
        initComponents();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        convertToLabel = new javax.swing.JLabel();
        ConvertFromLabel = new javax.swing.JLabel();
        convertFromBox = new javax.swing.JComboBox<>();
        convertToBox = new javax.swing.JComboBox<>();
        temperatureBox = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        answerBox = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));

        titlePanel.setBackground(new java.awt.Color(0, 102, 153));

        title.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Temperature Converter");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        bodyPanel.setBackground(new java.awt.Color(102, 102, 255));

        convertToLabel.setForeground(java.awt.Color.white);
        convertToLabel.setText("Convert To:");

        ConvertFromLabel.setForeground(java.awt.Color.white);
        ConvertFromLabel.setText("Convert From:");

        convertFromBox.setBackground(new java.awt.Color(153, 153, 255));
        convertFromBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<--Choose a unit-->", "Celsius", "Fahrenheit", "Kelvin", " " }));

        convertToBox.setBackground(new java.awt.Color(153, 153, 255));
        convertToBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<--Choose a unit-->", "Celsius", "Fahrenheit", "Kelvin", " " }));

        temperatureBox.setBackground(new java.awt.Color(153, 153, 255));

        button.setBackground(new java.awt.Color(153, 153, 255));
        button.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        button.setText("Convert");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        answerBox.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        answerBox.setForeground(java.awt.Color.white);
        answerBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConvertFromLabel)
                    .addComponent(convertFromBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convertToBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertToLabel))
                .addGap(64, 64, 64))
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(temperatureBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(answerBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConvertFromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convertFromBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertToBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(temperatureBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(answerBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
    
        try{
            String fromBox ="";
            String toBox="";
            if (!(convertFromBox.getSelectedIndex()==0)){
            fromBox =(String) convertFromBox.getSelectedItem();
            }
            else{
                JOptionPane.showMessageDialog(bodyPanel,"Please select an option from the dropdown menu!");
            }
            if (!(convertToBox.getSelectedIndex()==0)){
            toBox = (String) convertToBox.getSelectedItem();
            }
            else{
                JOptionPane.showMessageDialog(bodyPanel,"Please select an option from the dropdown menu!");
            }
            double temp =Double.parseDouble(temperatureBox.getText());
            System.out.println(temp);
            String k="Kelvin";
            String c = "Celsius";
            String f = "Fahrenheit";
            double converted = 0;
            
            
            if (fromBox.equals(c) && toBox.equals(k)){
                converted = temp+273.15;                
            }
            if (fromBox.equals(k) && toBox.equals(c)){
                converted = temp-273.15;
            }
            if (fromBox.equals(f) && toBox.equals(c)){
                converted = (temp-32)*5/9;
            }
            if (fromBox.equals(c) && toBox.equals(f)){
                converted = (temp*1.8)+32;
                System.out.println(converted);
            }
            if (fromBox.equals(f) && toBox.equals(k)){
                converted = ((temp-32)*5/9)+273.15;
            }
            if (fromBox.equals(k) && toBox.equals(f)){
                converted = (temp * 1.8)-459.67;
            }
            if (fromBox.equals(toBox)){
               JOptionPane.showMessageDialog(bodyPanel,"Please try selecting different units for conversion."); 
            }
            answerBox.setText("Value of "+ temp+ " in "+ fromBox+ " is " +converted+ " in "+toBox);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(bodyPanel,"Invalid Input, Please try entering a numeric value!");
            clear();
        }
        
    }//GEN-LAST:event_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConverterGUI().setVisible(true);
            }
        });
               
    }
    public void clear(){
        temperatureBox.setText("");
        convertToBox.setSelectedIndex(0);
        convertFromBox.setSelectedIndex(0);
    
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConvertFromLabel;
    private javax.swing.JLabel answerBox;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton button;
    private javax.swing.JComboBox<String> convertFromBox;
    private javax.swing.JComboBox<String> convertToBox;
    private javax.swing.JLabel convertToLabel;
    private javax.swing.JTextField temperatureBox;
    private javax.swing.JLabel title;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}


